### ISSUE TITLE
effective java 2nd edition

### ISSUE THREAD

**Issue by ryc8889** [mgp/book-notes#9]
Thanks for your book-notes i found them very useful as a quick summary of the important pieces of each item. 
Is there a complete version of effective java 2nd edition? There's a couple of items missing for concurrency and the serialization chapter

Also do you plan on updating this when the 3rd edition comes out? Just curious

**Comment by mgp** [comment]
Hey @ryc8889, sorry for the late response.

Huh, I'm surprised I didn't finish the concurrency chapter. I can go back and finish that, but I'm keeping pretty busy these days, and so I can't say when I'll do that by... But yeah, I can do this eventually. (If you really want to learn about concurrency, I highly recommend reading Java Concurrency in Practice. I have partial notes for that at https://github.com/mgp/book-notes/blob/master/java-concurrency-in-practice.markdown.)

And I won't finish the serialization chapter, sorry. Serialization is a feature that I've never used.

And I enjoyed this book a lot, and so there's a good chance that I'll buy the 3rd edition and update this eventually, yes!

**Comment by ryc8889** [comment]
I read it myself (and i have the concurrency in practice book) I was just curious on your take since i actually use your notes as a little cheatsheet for myself haha. 

I'm also looking forward to the 3rd edition and seeing the author's take on the new concurrency utilities and the new features since java 6.

Thanks again for all your book-notes they've been great!
